
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: projectmembers.ca-gip.github.com
spec:
  group: ca-gip.github.com
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
  names:
    singular: projectmember
    plural: projectmembers
    listKind: ProjectMembersList
    kind: ProjectMember
    shortNames:
      - pm
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        dn:
          type: string
        username:
          type: string
        mail:
          type: string
  additionalPrinterColumns:
    - name: Mail
      type: string
      description: Mail of the member
      JSONPath: .mail
    - name: DN
      type: string
      description: DN of the member
      JSONPath: .dn
